---
title: "Prepare SPAT codes for USAGI"
output: 
    github_document:
        df_print: tibble
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(readxl)
```

## Load

```{r load, message=FALSE, warning=FALSE}
spat_standard <- read_excel("./SPAT_FIN_THLplusENG.xlsx")
freq_spat_finngen <- read_csv("./freq_spat_finngen.csv") %>% select(-X1)
```


Number of codes in each source: 
```{r}
spat_standard %>%  nrow()
freq_spat_finngen %>%  nrow()
```
Number of SPAT events in finngen :
```{r}
n_events_finngen <- freq_spat_finngen$n_codes %>% sum()

number(n_events_finngen)
```


## Study codes in FinnGen

```{r}
finngen_join <- left_join(freq_spat_finngen %>% rename(CodeId=CODE1), spat_standard, by = "CodeId") %>%
  mutate( freq_finngen_per=percent(n_codes/n_events_finngen))
```

**How many codes labeled as SPAT in FinnGen are not in the SPAT standard ?**
```{r paged.print=TRUE}
no_finngen_standard <- finngen_join %>% filter(is.na(ShortName)) %>% select(CodeId, ShortName, CodeId, n_codes) 
```

There are `r no_finngen_standard %>%  nrow()` codes not found in the standard:

```{r paged.print=TRUE}
no_finngen_standard 
```

Great, only typos and the -1, -2 error codes


```{r}
finngen_standard <- finngen_join %>% filter(!is.na(ShortName)) %>% select(CodeId, n_codes, freq_finngen_per, LongName, ENGLongName, Description, HierarchyLevel, BeginningDate, ExpiringDate, LastModifiedDate)
finngen_standard
```


```{r}
finngen_standard <- finngen_standard %>% mutate_if(is.numeric, ~if_else(is.na(.), rep(0, length(.)), .)) 

write_csv(finngen_standard, "./standard_spat_with_freq.csv")
```



