---
title: "Study VNRO"
output: 
    github_document:
        df_print: tibble
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(readxl)
library(feather)
library(ggupset)
library(UpSetR)
```

## Load

```{r load, message=FALSE, warning=FALSE}
atc_omop <- read_csv("OMOP_ATC.csv") %>% 
  rename(code = concept_code)

atc_change <- read_csv("atc_modifications.csv") %>% 
  mutate_at(vars(previous_atc_code, new_atc_code), str_replace, "\\s[:digit:]+\\)", "")

freq_atc_finngen <- read_csv("../1_source_codes_freq/freq_purch_finngen.csv") %>% select(-X1) %>% 
  rename(freq_finngen=n_codes) %>% 
  group_by(CODE1) %>% summarise(freq_finngen=sum(freq_finngen)) %>% arrange(-freq_finngen) 
```



# Study Finngen

Number of codes in each source: 
```{r}
atc_omop %>%  nrow()
freq_atc_finngen %>%  nrow()


n_events_finngen <- freq_atc_finngen$freq_finngen %>% sum()
```

```{r}
 finngen_join <- full_join(freq_atc_finngen %>% rename(code = CODE1), 
                           atc_omop,
                           by = c("code"))
```


**How many codes labeled as atc in FinnGen are not in the OMOP standard ?**
```{r paged.print=TRUE}
no_finngen_standard <- finngen_join %>% filter(is.na(concept_id)) %>% select(code, freq_finngen ) %>%
  mutate( freq_finngen_per=percent(freq_finngen/n_events_finngen))

no_finngen_standard
```


```{r}

no_finngen_standard %>% filter(!str_detect(code, "^E00"))

```


**What vocabualy are codes starting with E ??**

**From Ari Ahola-Olli:** E can be found from there. But the reason why they are not in WHO database is that they are not actual drugs.

```{r}
left_join(no_finngen_standard, 
          atc_change %>%  mutate(code = previous_atc_code),
          by="code") %>% 
  filter(is.na(previous_atc_code))
```






```{r}
right_join(atc_omop %>% select(code, concept_id), 
          atc_change %>%  mutate(code = previous_atc_code),
          by="code") %>% 
  filter(is.na(concept_id)) %>% 
  write_excel_csv("atc_modified_not_in_OMOP.xls")
```
















```{r}
aa <- read_csv("../1_source_codes_freq/freq_purch_finngen.csv") %>% select(-X1) %>% 
  rename(freq_finngen=n_codes) %>% 
  filter(str_detect(CODE1, "^E000")) %>% rename(atc=CODE1, vnro=CODE3) 
```










