---
title: "ICPC mappings"
output: 
    github_document:
        df_print: kable
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
source("../../lib/read_tables.r")

path_vocabulary_tables <- "../../lib/OMOP_VOCABULARY/"

# Document variables 
N_TOPS <- 10
```

## Mapping type : to ICD10 

Source table has a column indicating the icd10fi equivalent 

```{r message=FALSE, warning=FALSE}
icpc_source <- read_csv("../1_source_vocabulary/CONCEPT_ICPC.csv") %>% 
  filter(domain_id!="Metadata")
```

```{r message=FALSE, warning=FALSE}
icd10fi_concept <- read_csv("../../ICD10fi/1_source_vocabulary/CONCEPT_ICD10fi.csv") %>% 
  filter(domain_id!="Metadata")
icd10fi_mapsto <- read_csv("../../ICD10fi/2_mapping_to_standard/CONCEPT_RELATIONSHIP_ICD10fi.csv")


# map icpc to icd10fi 
icpc_mapping_idc10fi <-  left_join(
  icpc_source, 
  icd10fi_concept %>% select(concept_id, concept_code) %>% 
    rename(concept_id_icd10 = concept_id, tmp_main_icd10fi = concept_code), 
  by="tmp_main_icd10fi"
)
```


```{r}
# map icd10fi to OMOP
icpc_mapping <-  left_join(
  icpc_mapping_idc10fi %>% 
    filter(!is.na(concept_id_icd10)) %>% 
    select(concept_id, valid_start_date, valid_end_date, concept_id_icd10), 
  icd10fi_mapsto %>% rename(concept_id_icd10 = concept_id_1), 
  by="concept_id_icd10"
) %>% 
  filter(!is.na(concept_id_2))
```


## Formating mappigs to OMOP


- For valid_start_date max of source concept and mapping concept is chosen 
- For valid_end_date min of source concept and mapping concept is chosen 


```{r}

# select max valid_start_date and min for valid_end_date 
icpc_mapsto <- icpc_mapping %>% 
  transmute(
    concept_id_1 = concept_id,
    concept_id_2 = concept_id_2,
    relationship_id = "Maps to",
    valid_start_date = pmax(valid_start_date.x, valid_start_date.y), 
    valid_end_date   = pmin(valid_end_date.x, valid_end_date.y), 
    invalid_reason = as.character(NA), 
    tmp_mapping_type = "ICD10fi", 
    tmp_domain_id_2 = tmp_domain_id_2   
  )


write_csv(icpc_mapsto, "CONCEPT_RELATIONSHIP_ICPC.csv")

icpc_mapsto %>%  head(N_TOPS)

```




## Recalculate domain 
```{r}
icpc_domain <- icpc_mapsto %>% 
  rename(concept_id = concept_id_1) %>% 
  group_by(concept_id) %>% 
  summarise(domain = str_c( sort(unique(tmp_domain_id_2))  , collapse = " "), .groups="drop") %>% 
  mutate(domain = str_replace(domain, "Condition Observation", "Condition/Obs" )) %>% 
  mutate(domain = str_replace(domain, "Condition Procedure", "Condition/Procedure" ))
  
```

```{r message=FALSE, warning=FALSE}
icpc_concept <- read_csv("../1_source_vocabulary/CONCEPT_ICPC.csv")

icpc_concept_new <- left_join(
  icpc_concept, 
  icpc_domain, 
  by="concept_id"
) %>% 
  mutate(domain_id = if_else(is.na(domain), domain_id, domain )) %>%
  select(-domain)

#overwrite
write_csv(icpc_concept_new, "../1_source_vocabulary/CONCEPT_ICPC.csv")

```

```{r}
icpc_concept_new %>% count(domain_id, sort=T)
```























