---
title: "ICPC mappings"
output: 
    github_document:
        df_print: kable
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
source("../../lib/read_tables.r")

path_vocabulary_tables <- "../../lib/OMOP_VOCABULARY/"

# Document variables 
N_TOPS <- 10
```

## Mapping type : to ICD10 

Source table has a collumn indicating the icd10 equivalent 

```{r}
icpc_source <- read_csv("../1_source_vocabulary/CONCEPT_ICPC.csv")
```




```{r}
#TODO in the future we should take from 3_mapping_table
ICD10fi_OMOP <- read_csv("../../ICD10fi/2_mapping_to_standard/OMOP_ICD10who.csv")

icpc2_auto_mapped <-  left_join(
  icpc2_standard, 
  ICD10fi_OMOP %>% rename(code=concept_code) %>% select(code, concept_id), 
  by="code"
)

icpc2_no_mapped <- icpc2_auto_mapped %>% filter(is.na(concept_id)) %>% count(ICPC_version) 

icpc2_auto_mapped <- icpc2_auto_mapped %>% 
  mutate(mappingStatus = if_else(!is.na(concept_id),"AUTO_MAPPED", "NOT_MAPPED"))

```



## Formating mappigs to OMOP

Mappings based on USAGI. 

- For valid_start_date max of source concept and mapped concept is chosen 
- For valid_end_date min of source concept and mapped concept is chosen 

```{r}
# load concept table
concept <- read_table_concept(path_vocabulary_tables)
```


```{r}
# join to nomeco concepts
icpcfi_mapping <- inner_join(
  icpcfi_concept %>% 
    select(concept_id, concept_code, valid_start_date, valid_end_date) %>% 
    rename(concept_id_1 = concept_id),
  icpc_after_usagi %>%  filter(mappingStatus == "APPROVED") %>% 
    select(sourceCode, conceptId) %>% 
    rename(concept_id_2 = conceptId, concept_code = sourceCode),
  by="concept_code"
) %>% select(-concept_code )



# join to mapped concepts 
icpcfi_mapping <- left_join(
  icpcfi_mapping, 
  concept %>% 
    select(concept_id, valid_start_date, valid_end_date) %>% 
    rename_all(str_c, "_2"), 
  by="concept_id_2"
)

# select max valid_start_date and min for valid_end_date 
icpcfi_mapsto <- icpcfi_mapping %>% 
  transmute(
    concept_id_1 = concept_id_1,
    concept_id_2 = concept_id_2,
    relationship_id = "Maps to",
    valid_start_date = pmax(valid_start_date, valid_start_date_2), 
    valid_end_date   = pmin(valid_end_date, valid_end_date_2), 
    invalid_reason = as.character(NA), 
    temp_mapping_type = "USAGI"
  )


write_csv(icpcfi_mapsto, "CONCEPT_RELATIONSHIP_ICPC.csv")

icpcfi_mapsto %>%  head(N_TOPS)

```

























